---
save_node_db: true
serial_port: /dev/ttyACM0
weather:
  conditions:
    humidity_entity_id: sensor.outdoor_humidity
    location_description: City of Poets, Hyperion
    temp_entity_id: sensor.outdoor_temperature
    url: http://homeassistant.local:8123
  forecast:
    url: https://api.weather.gov/gridpoints/ALY/72,63/forecast
    user_agent: (example.com, example@example.com)
bot:
  active: true
  auto_accept_contacts: true
  commands:
    .about: I'm a MeshCore bot 🤖
    .conditions: get_weather_conditions
    .forecast: get_weather_forecast
    .help: 'Available commands: .about .conditions .forecast .help .ping .seen'
    .ping: pong!
    .seen: get_seen_nodes
workers:
  - type: advert
    active: true
    cron: 0 */6 * * *
    dispatch: get_advert_worker
  - type: beacon
    active: true
    channel: public
    cron: 0 0,12 * * *
    dispatch: get_beacon_worker
    text: Come join our local Discord! https://www.example.com
  - type: weather_conditions
    active: false
    channel: public
    cron: 0 * * * *
    dispatch: get_weather_conditions_worker
  - type: weather_forecast
    active: true
    channel: public
    cron: 15 8,20 * * *
    dispatch: get_weather_forecast_worker
